public class Constants {
    public static final String IMAGE_API_INTEGRATION_ENDPOINT = 'ImageApi';
    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String CONTENT_TYPE_APP_JSON = 'application/json';
    public static final String REQUEST_GET_METHOD = 'GET';
    public static final Integer API_SUCCESS_CODE = 200;
    public static final Integer API_BAD_REQUEST_CODE = 400;
    public static final Integer TEXT_AREA_LONG_SIZE = 131072;
}